### ISSUE TITLE
Window controls broken in FF133 when sidebery tweak active (hide-tabs-bar.css)

### ISSUE THREAD

**Issue by alixyz-1** [Loskir/EdgyArc-fr#8]
Window controls (minimise, maximise, and close) do not function when sidebery sidebar is open and tweak enabled to hide top tab bar.

It looks like an issue with hide-tabs-bar.css as per this comment in the "main" repo for EdgyArc-fr: https://github.com/artsyfriedchicken/EdgyArc-fr/issues/85#issuecomment-2508952825

- OS: Manjaro Linux
- Desktop: KDE Plasma 6.2.4
- Windowing system: Wayland
- Browser version: Firefox 133

**Comment by Loskir** [comment]
Hello! Could you share your config? Can't seem to reproduce

**Comment by Loskir** [comment]
I'm running macos currently. Can you make a video with the problem?

**Comment by SJ50** [comment]
Same issue in windows 11. 
I can not select buttons like shown in above videos.

**Comment by craftycorvid** [comment]
Replacing `hide-tabs-bar.css` with the version from edge-frfox fixes the issue for me: https://github.com/bmFtZQ/edge-frfox/blob/main/chrome/tweaks/hide-tabs-bar.css

**Comment by craftycorvid** [comment]
There's another issue with the nav-bar in Windows when edge-sidebar is enabled. This filter gets applied twice to it, so it looks darker than the rest of the UI.

```css
  #main-window::after,
  #browser::before {
    content: "";
    display: block;
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    pointer-events: none;
    background-color: light-dark(#cdcdcd, #444) !important;
    opacity: 0.3;
  }
```

![image](https://github.com/user-attachments/assets/cfd4bb0a-2f57-493f-b4c3-18bf32903981)

Deleting `#browser::before` fixes it, but I don't know if that's a universal solution.
